# Generated by Django 4.0.4 on 2022-06-05 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creador_id', models.IntegerField()),
                ('creador_usuario', models.TextField(max_length=50)),
                ('mensaje', models.TextField(max_length=50)),
                ('fecha', models.DateTimeField()),
            ],
        ),
    ]
