# Generated by Django 4.0.4 on 2022-06-05 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0002_anuncio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='mensaje',
            field=models.TextField(max_length=500),
        ),
    ]
