# Generated by Django 4.0.4 on 2022-06-05 19:36

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0003_alter_anuncio_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='mensaje',
            field=tinymce.models.HTMLField(),
        ),
    ]
