# Generated by Django 4.0.4 on 2022-06-03 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDesafio', '0002_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.TextField(max_length=50)),
                ('comentario', models.TextField(max_length=500)),
                ('fecha', models.DateField()),
                ('posteoId', models.IntegerField()),
            ],
        ),
    ]
