# Generated by Django 4.0.4 on 2022-06-03 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDesafio', '0003_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
