# Generated by Django 4.0.4 on 2022-06-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDesafio', '0005_rename_item_posteo_alter_comentario_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteo',
            name='subtitulo',
            field=models.TextField(default='Metal', max_length=50),
            preserve_default=False,
        ),
    ]
