# Generated by Django 4.0.4 on 2022-06-05 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppDesafio', '0006_posteo_subtitulo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Animal',
        ),
        migrations.DeleteModel(
            name='Donacion',
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
